# See https://pre-commit.com for more information
exclude: '\S*.map'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: docs/source/developer_reference/
    -   id: end-of-file-fixer
        exclude: docs/source/developer_reference/
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-toml
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.0
    hooks:
    -   id: black
        args: ["--line-length", "100"] # Adjust the max line length value as needed.
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--line-length", "100", "--profile", "black"]
