# This file may be used to create a conda environment using:
# $ conda env create -f <this file>

name: gprMax-devel
dependencies:
- python>3.7
- colorama
- cython
- h5py
- jinja2
- jupyter
- matplotlib
- numpy<2
- pip
- psutil
- scipy

- pip:
  - humanize
#  - mpi4py
#  - mpi4py-fft
  - numpy-stl
#  - pyobjc-framework-metal
#  - pycuda
#  - pyopencl
  - terminaltables
  - tqdm
